### ISSUE TITLE
如何在同一服务器部署多个hexo

### ISSUE THREAD

**Issue by chinobing** [YuJianghao/winwin-hexo-editor#13]
如题

**Comment by YuJianghao** [comment]
如果您指的是部署多个winwin-hexo-editor的话，直接单独部署多个服务到不同端口就可以了。

如果部署多个hexo博客的话可以参考[hexo文档](https://hexo.io/zh-cn/docs/one-command-deployment)

**Comment by chinobing** [comment]
对，就是指部署多个winwin-hexo-editor。 你意思是将winwin-hexo-editor分别独立放进不同的文件夹，然后执行`bash install.sh` `npm run start`等命令并指定不同的端口，是这样吗？

**Comment by YuJianghao** [comment]
是的
