### ISSUE TITLE
It showed that the deploy failed, but the deploy succeeded.

### ISSUE THREAD

**Issue by LunaGao** [YuJianghao/winwin-hexo-editor#3]
I clicked the deploy button, it showed that the deploy failed, but the deploy succeeded.

I'm using this deploy script:
https://github.com/HakurouKen/hexo-deployer-shell

**Comment by YuJianghao** [comment]
Could I have your notification message and response body, or any error messages? So that I can find it's problem with client or with server.

response body should looks like:
```json
{
    "success":false,
    "message":"xxx"
}
```

**Comment by LunaGao** [comment]
![1123](https://user-images.githubusercontent.com/5066920/77570344-98119f00-6f06-11ea-8678-ba9cc36c11f7.png)

QQ(591304836)?

**Comment by YuJianghao** [comment]
Friend request sent~
