### ISSUE TITLE
按钮点击延迟，新特性请求｜Action delay and new feature request

### ISSUE THREAD

**Issue by declan-haojin** [YuJianghao/winwin-hexo-editor#8]
我之前尝试了`hexo-admin`但是出现各种问题最终放弃了，搭建了一个vscode网页版但是无法部署，没想到遇见了大佬您的repo！！！感谢大佬！！！居然还有ios端，简直太棒了！！！UI好好看！！！

---

蒟蒻有几个建议：
- 点击按钮的时候卡顿延迟比较大，不知道是不是我服务器的问题？
- 是否可以专门增加一个hexo generate按钮，因为我是直接部署在云服务器上，不上传到github。（虽然根据#2的方法可以把部署按钮改成生成按钮）
- 请求大佬把右划编辑改成一个醒目的按钮，这电脑端滑动操作有点奇怪，第一次使用半天不知道怎么编辑
- 可否适当放宽最左边一栏的宽度，或者内容过长的时候用省略号代替，如下图（当分类名称过长时看着就比较奇怪）：
   
![image](https://user-images.githubusercontent.com/56029057/85204443-184d7200-b347-11ea-8dd2-bb817cbb2288.png)

***最后，再次感谢大佬！期待更多更新！***

**Comment by YuJianghao** [comment]
感谢star～

- 按钮延迟，一般是因为网速比较慢。我也会尽力优化的。
- 双击文章预览页也可以编辑。更方便的编辑按钮会在以后慢慢更新。

其他功能记下了，会慢慢加的莫着急。

**Comment by declan-haojin** [comment]
谢谢大佬！

**Comment by declan-haojin** [comment]
另外IOS端app我一直显示`Network Error`请问有什么解决方案吗？

**Comment by YuJianghao** [comment]
@declan-haojin 
ios端还在开发中，具体进度可以问 @maomishen
QQ群：590355610

**Comment by declan-haojin** [comment]
谢谢！

**Comment by YuJianghao** [comment]
已解决
