### ISSUE TITLE
新建文章，md文件名称会变成乱码 | Post file names are garbled

### ISSUE THREAD

**Issue by declan-haojin** [YuJianghao/winwin-hexo-editor#9]
![image](https://user-images.githubusercontent.com/56029057/85913845-c89d0800-b86a-11ea-947e-37511a34a5de.png)

md文件的前缀时间都是正确的，而之后的文章题目是乱码。但是打开文件`title:`关键字是正确的题目。

谢谢！

**Comment by YuJianghao** [comment]
文件名取决于文章的slug和你的hexo配置，我默认的slug是一串随机数（也就是你说的乱码）

**Comment by declan-haojin** [comment]
那有啥办法变成文章标题吗

**Comment by YuJianghao** [comment]
目前还没，有需要的话我后期更新加上吧。可以先临时手工改文件名

**Comment by declan-haojin** [comment]
谢谢！

**Comment by YuJianghao** [comment]
已解决
